### ISSUE TITLE
wrong PC IP

### ISSUE THREAD

**Issue by CelesteBlue-dev** [phonorepo/psx-cpl#2]
In the app it shows for PC IP : 192.168.58.1.
But my PC IP is 192.168.0.30.
Can I change this IP or what to do ?

**Comment by phonorepo** [comment]
Hi thanks for testing and reporting back.
Good catch, would be good to be able to at least edit it manually.

It is a drop down and should list all your Ethernet-IPs.
But this might be too limited as I think it will not add Wireless IPs. 
I never had the time to test it with wireless. 

I will make the modifications the next days.

Source where this happens is here:
https://github.com/phonorepo/psx-cpl/blob/master/psx-cpl/MainWindow.xaml.cs#L496
https://github.com/phonorepo/psx-cpl/blob/master/psx-cpl/network.cs#L19

**Comment by phonorepo** [comment]
OK I already implemented the changes, could you try it now?

**Comment by phonorepo** [comment]
just updated it and made the program more usable

**Comment by CelesteBlue-dev** [comment]
I have many issues while using your tool.
Port choice is weird because I enter 9023 but when I click on run payload on your tool it displays a error of port 5XXX.
I will try version 1.4.0.

**Comment by phonorepo** [comment]
The port is automatically changed if you select the firmware version currently.
So at start it is set to 5054.
If you then switch to Firmware 4.05 it will be set to 9020.

In the next version I changed it to be the last entry in the firmware list so it will start with v4.05 + Port 9020.
But additonally I started to implement custom user settings to define some defaults like default port, default html file to deliver if the PS4 Guide is started, default payload ...

**Comment by CelesteBlue-dev** [comment]
I have both 1.76 and 4.05 PS4.
My PC is connected by WIFI to internet and my PS4s are connected by LAN to internet.

**Comment by phonorepo** [comment]
That's great to have both, 4.05 and 1.76. I had to upgrade my one and only ps4 to 4.05 now.

Do you have still problems with v1.0.4?
Is it now showing all correct IPs in the drop down for you?
And if you enter a port manually and then click send payload it definetly should use that port, if not let me know! I want to fix it so that it is working for you.

One more thing where you might be able to help me or ask someone that might know it:
Do you know where on the ps4 the root certificates are stored and if it is possible to add own (for using it with the proxy)?
I will be able to try and search for it maybe this or next weekend earliest.

**Comment by phonorepo** [comment]
certs found: /system/common/cert/CA_LIST.cer
